services:
  todosDB:
    image: postgres:latest
    container_name: todos-db
    restart: always
    ports:
      - "5432:5432" # Comunicación entre puertos.
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todos
    volumes:
      - ./postgres:/var/lib/postgresql
